services:

  nginx:
    build: ./nginx
    image: nginx:latest
    container_name: ng-main
    ports:
      - "81:80"
    depends_on:
      - app1
      - app2
      - app3

  app1:
    build: ./app
    image: ashrith2727/ng-app:v1
    container_name: ng-app
    depends_on:
      - postgres
      - mysql
      - redis

  app2:
    build: ./app
    image: ashrith2727/ng-app2:v1
    container_name: ng-app2
    depends_on:
      - postgres
      - mysql
      - redis

  app3:
    build: ./app
    image: ashrith2727/ng-app3:v1
    container_name: ng-app3
    depends_on:
      - postgres
      - mysql
      - redis

  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_DB: postgresdb
      POSTGRES_USER: krishna
      POSTGRES_PASSWORD: 1729
    volumes:
      - ./db/postgres/data:/var/lib/postgresql/data

  mysql:
    image: mysql:8
    container_name: mysql
    environment:
      MYSQL_DATABASE: mysqldb
      MYSQL_USER: rama
      MYSQL_PASSWORD: 1729
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./db/mysql/data:/var/lib/mysql

  redis:
    image: redis:7
    container_name: redis
