name: CI-CD Pipeline

on:
  push:
    branches:
      - main

env:
  IMAGE_NAME: ashrith2727/ng-app

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Image
        run: |
          docker build -t $IMAGE_NAME:${{ github.sha }} ./app

      - name: Push Image
        run: |
          docker push $IMAGE_NAME:${{ github.sha }}

      - name: Setup Kubeconfig
        run: |
          echo "${{ secrets.KUBECONFIG }}" | base64 --decode > kubeconfig
        env:
          KUBECONFIG: kubeconfig

      - name: Update Deployment
        run: |
          kubectl set image deployment/python-app \
          python-app=$IMAGE_NAME:${{ github.sha }} \
          --kubeconfig=kubeconfig

      - name: Verify Rollout
        run: |
          kubectl rollout status deployment/python-app \
          --kubeconfig=kubeconfig
